name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: jdx/mise-action@v5.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache: true
      - run: uv sync --extra dev
      - run: mise run check
